name: Validations v4 (testing)

on:
  pull_request_target:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.2]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'reichlab/covid19-forecast-hub-validations'
        ref: 'issue-29'
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
#     - run: npm install
    - name: Setup pipenv
      run: pip3 install pipenv
    - name: Install python dependencies 
      run: pipenv install
    - name: Validations output
      run: pipenv run python main.py
      env:
        GH_TOKEN: ${{ github.token }}
    
    # Run and check for automerge
    #- name: Automerge check
    #  uses: "pascalgn/automerge-action@v0.13.1"
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
    #    MERGE_LABELS: "automerge,data-submission,!other-files-updated,!metadata-change,!forecast-updated,!viz,!code"
