name: Validate a single/pattern forecast file
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Forecast file name'
        required: true

jobs:
  validate_forecast:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: npm install
    - run: pip3 install -r visualization/requirements.txt
    - run: python3 code/validation/validate_single_forecast_file.py ${{ github.event.inputs.name }}
      env:
        Z_USERNAME: ${{ secrets.Z_USERNAME}}
        Z_PASSWORD: ${{ secrets.Z_PASSWORD}}
        GH_TOKEN: ${{secrets.GH_TOKEN}}
